---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackgame-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stackgame
  template:
    metadata:
      labels:
        app: stackgame
    spec:
      containers:
      - name: stackgame
        image: prinxehasi/stackgamev1:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: stackgame-svc
spec:
  selector:
    app: stackgame
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
